# Generated by Django 3.1.3 on 2020-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('given_course', models.CharField(max_length=30)),
                ('departament', models.CharField(max_length=30)),
            ],
        ),
    ]
